### ISSUE TITLE
Would it be possible to consider a different open-source license?

### ISSUE THREAD

**Issue by tleonhardt** [psycopg/psycopg3#1]
Many large companies view GPL and LGPL licenses as toxic and do not allow their usage.  Would it be possible to consider releasing `psycopg3` under a more corporate-friendly license like MIT, BSD, or Apache?

**Comment by dvarrazzo** [comment]
Yes, as long as there is corporate backing for the project.

**Comment by cheesycod** [comment]
I would like this as well

**Comment by dvarrazzo** [comment]
No interest on a different license from anyone who has been willing to contribute to the project. The latest events (Elasticsearch and several other discontent around Amazon behaviour) should demonstrate that BSD-style licenses are not viable.

I will release my work with the license I believe in.

**Comment by pauloxnet** [comment]
I totally agree with you @dvarrazzo

**Comment by tony** [comment]
@dvarrazzo Can you make sure the contributors sign a CLA so a license change is possible in the future if funding happens?  That keeps the possibility open.

And hopefully corporate sponsorships or funding does materialize

**Comment by dvarrazzo** [comment]
Hi @tony 

Thank you but no, I am not interested in setting up a CLA. It is bureaucratic overhead and a deterrent to contributions I don't wish to have in this project.
