### ISSUE TITLE
Import fails on PyPy

### ISSUE THREAD

**Issue by DzigaV** [psycopg/psycopg3#24]
Installed successfully:

```
pypy3 -mpip install git+https://github.com/psycopg/psycopg3.git#subdirectory=psycopg3
Defaulting to user installation because normal site-packages is not writeable
Collecting git+https://github.com/psycopg/psycopg3.git#subdirectory=psycopg3
  Cloning https://github.com/psycopg/psycopg3.git to /tmp/pip-req-build-38w058qk
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied: typing-extensions in /root/.local/lib/pypy3.6/site-packages (from psycopg3==2.99.0) (3.7.4.3)
```

But the import fails:

```
Traceback (most recent call last):
  File "app.py", line 6, in <module>
    import psycopg3
  File "/root/.local/lib/pypy3.6/site-packages/psycopg3/__init__.py", line 7, in <module>
    from . import pq
  File "/root/.local/lib/pypy3.6/site-packages/psycopg3/pq/__init__.py", line 102, in <module>
    import_from_libpq()
  File "/root/.local/lib/pypy3.6/site-packages/psycopg3/pq/__init__.py", line 99, in import_from_libpq
    raise ImportError("no pq wrapper available")
ImportError: no pq wrapper available
```

Any ideas?

**Comment by DzigaV** [comment]
Digging in. This is the cause:

`AttributeError: module 'ctypes' has no attribute 'pydll'`

**Comment by dvarrazzo** [comment]
I haven't worked at all with PyPy. If it doesn't support ctypes you may be better off installing the C wrapper, as cython _I think_ supports it.

The option I have on the plate for PyPy is to create a pq wrapper using cffi (https://www.varrazzo.com/blog/2020/05/19/a-trip-into-optimisation/). Creating a trivial one, very similar to the ctypes one, should be a simple, if a bit tedious, task

In other news, I'm improving the pq import machinery, so an error like yours should be reported as:

```
ImportError: Error importing plugin "tests.fix_faker": no pq wrapper available.
Attempts made:
- error importing 'c' wrapper: No module named 'psycopg3_c'
- error importing 'binary' wrapper: No module named 'psycopg3_binary'
- error importing 'python' wrapper: module 'ctypes' has no attribute 'pydll'
```

**Comment by dvarrazzo** [comment]
You can try the following, but please know that if it works is for sheer luck and all cython merits:

```
pypy3 -mpip install git+https://github.com/psycopg/psycopg3.git#subdirectory=psycopg3_c
```

and see if the c wrapper works with PyPy. Otherwise it will have to wait for someone to implement a cffi wrapper: I'm happy to help and support whoever wants to do it, but in term of personal time I have other tasks with higher priority at the moment.

**Comment by DzigaV** [comment]
I actually "fixed" it by changing

`pq = ctypes.pydll.LoadLibrary(libname)`

to

`pq = ctypes.cdll.LoadLibrary(libname)`

I'll wait the the CFFI wrapper, glad to hear it's planned! I'm a year away from needing it fortunately :-)

**Comment by dvarrazzo** [comment]
Uhm, actually it seems that `cdll` would be a better choice than `pydll`, as the libpq is a C library and all its function can run without the GIL. I don't know about the ones taking callback arguments though.

I have tried running the test suite and it didn't crash, so it's actually promising: I could replace `pydll` with `cdll` and see if things hold.

**Comment by dvarrazzo** [comment]
I've been using `cdll` all the day and didn't find problem, so it will land in master too. Thank you for the tip!
