### ISSUE TITLE
cur.executemany() doesn't take a "prepare" argument

### ISSUE THREAD

**Issue by DzigaV** [psycopg/psycopg3#31]
I just ran into this problem.

For consistency with execute(), shouldn't executemany() provide the same control over preparation?

**Comment by dvarrazzo** [comment]
No, executemany will do it's best to go fast, so it does prepare regardless. If I get how to do pipelinnjng it will use that, if it proves more efficient, etc.

Have you got an use case why you would need no prepare for it? Is there something you can have from executemany by not by putting execute in a loop?

**Comment by DzigaV** [comment]
> Is there something you can have from executemany by not by putting execute in a loop?

No, I was just using it as a convenience function.

I understand your reasoning and will close the issue.
