### ISSUE TITLE
No select.EPOLLONESHOT under macOS

### ISSUE THREAD

**Issue by jacopofar** [psycopg/psycopg3#34]
Hello,
I wanted to try psycopg3 and found it seems not to work in macOS.

This is the error when importing psycopg3:

```
Traceback (most recent call last):
  File "/Users/jacopo/projects/pgtest/src/ingest_into_postgres.py", line 1, in <module>
    import psycopg3
  File "/Users/jacopo/projects/pgtest/.venv/lib/python3.9/site-packages/psycopg3/__init__.py", line 9, in <module>
    from .copy import Copy, AsyncCopy
  File "/Users/jacopo/projects/pgtest.venv/lib/python3.9/site-packages/psycopg3/copy.py", line 22, in <module>
    from .generators import copy_from, copy_to, copy_end
  File "/Users/jacopo/projects/pgtest.venv/lib/python3.9/site-packages/psycopg3/generators.py", line 25, in <module>
    from .waiting import Wait, Ready
  File "/Users/jacopo/projects/pgtest/.venv/lib/python3.9/site-packages/psycopg3/waiting.py", line 200, in <module>
    Wait.R: select.EPOLLONESHOT | select.EPOLLIN,
AttributeError: module 'select' has no attribute 'EPOLLONESHOT'
```
I'm using Python 3.9 under macOS 11.2, and installing it from the repo

**Comment by dvarrazzo** [comment]
Ah I see.

Can you try to apply the following diff:
```diff
diff --git a/psycopg3/psycopg3/waiting.py b/psycopg3/psycopg3/waiting.py
index bfab413..e607024 100644
--- a/psycopg3/psycopg3/waiting.py
+++ b/psycopg3/psycopg3/waiting.py
@@ -196,13 +196,6 @@ async def wait_conn_async(gen: PQGenConn[RV]) -> RV:
         return rv
 
 
-poll_evmasks = {
-    Wait.R: select.EPOLLONESHOT | select.EPOLLIN,
-    Wait.W: select.EPOLLONESHOT | select.EPOLLOUT,
-    Wait.RW: select.EPOLLONESHOT | select.EPOLLIN | select.EPOLLOUT,
-}
-
-
 def wait_epoll(
     gen: PQGen[RV], fileno: int, timeout: Optional[float] = None
 ) -> RV:
@@ -247,5 +240,12 @@ if (
     is selectors.EpollSelector
 ):
     wait = wait_epoll
+
+    poll_evmasks = {
+        Wait.R: select.EPOLLONESHOT | select.EPOLLIN,
+        Wait.W: select.EPOLLONESHOT | select.EPOLLOUT,
+        Wait.RW: select.EPOLLONESHOT | select.EPOLLIN | select.EPOLLOUT,
+    }
+
 else:
     wait = wait_selector
```

If it work I'll commit it to master

**Comment by dvarrazzo** [comment]
I have applied the diff to master. Please let us know if it fixes your problem. There might be others as macOS is untested

**Comment by jacopofar** [comment]
The error changed. Now it is:

```
  File "/Users/jacopo/projects/pgtest/.venv/lib/python3.9/site-packages/psycopg3/waiting.py", line 240, in <module>
    is getattr(selectors, 'EpollSelector')
AttributeError: module 'selectors' has no attribute 'EpollSelector'
```

On my system `dir(selector)` shows these attributes:

```'ABCMeta', 'BaseSelector', 'DefaultSelector', 'EVENT_READ', 'EVENT_WRITE', 'KqueueSelector', 'Mapping', 'PollSelector', 'SelectSelector', 'SelectorKey', '_BaseSelectorImpl', '_PollLikeSelector', '_SelectorMapping', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', '_can_use', '_fileobj_to_fd', 'abstractmethod', 'math', 'namedtuple', 'select', 'sys'```

It seems [epoll is available only on Linux](https://docs.python.org/3/library/select.html#select.epoll), but if I change the code to `getattr(selectors, 'EpollSelector', None)` in the check then it falls back to `wait_selector` and I can run the example code without problems.

**Comment by dvarrazzo** [comment]
Thank you, good to know. I will make this changeset too in master.
