### ISSUE TITLE
Can psycopg3 support opengauss database

### ISSUE THREAD

**Issue by wj-Mcat** [psycopg/psycopg3#40]
[openGauss](https://opengauss.org/en/) is an open source relational database management system that is released with the Mulan PSL v2. with the kernel derived from PostgreSQL.

If you can support opengauss databse, it will be great for python driver. How do you think about?

**Comment by dvarrazzo** [comment]
Hello,

This project is funded by sponsorships. If your company is willing to sponsor the project we can consider some form of explicit support. You are welcome to get in touch for further details.
