### ISSUE TITLE
Any plan for ssl-mode connection with server?

### ISSUE THREAD

**Issue by wj-Mcat** [psycopg/psycopg3#41]
Is there any secure connection with server. I can find any documentation for it.

So, can anybody help me ?

**Comment by dvarrazzo** [comment]
All the [libpq parameters](https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-PARAMKEYWORDS) are supported and passed through by `Connection.connect()`/`psycopg3.connect()`, either in *conninfo* or as keyword argument: [see docs](https://www.psycopg.org/psycopg3/docs/api/connections.html#psycopg3.Connection.connect).
