### ISSUE TITLE
how to start replication from beginning 

### ISSUE THREAD

**Issue by thecloudgeek** [psycopg/psycopg3#42]
I'm trying to understand how I can start logical replication from the beginning. I have this all setup...but I'm only capturing new changes to the tables but not the current data thats in there. I'm assuming I need to specify the LSN to start at (doc: https://www.psycopg.org/docs/extras.html?highlight=loggingconnection#psycopg2.extras.ReplicationMessage.data_start)...but how does one get the start of LSN?

by basic python script looks like this:

```
import json
import random
import calendar
import time
from datetime import datetime
import psycopg2
from psycopg2.extras import LogicalReplicationConnection

my_connection  = psycopg2.connect(
                   "dbname='dbname' host='host.com' user='user' password='pass'" ,
                   connection_factory = LogicalReplicationConnection)
cur = my_connection.cursor()
cur.drop_replication_slot('wal2json_test_slot')
cur.create_replication_slot('wal2json_test_slot', output_plugin = 'wal2json')
cur.start_replication(slot_name = 'wal2json_test_slot', options = {'pretty-print' : 1}, decode= True)

def consume(msg):
    print (msg.payload)

cur.consume_stream(consume)
```

**Comment by dvarrazzo** [comment]
Hello,

> I'm trying to understand how I can start logical replication from the beginning

Typically, you cannot, unless you have all the WAL files from the beginning. You need a different way to create a first sync.

Your question cannot have further answers in this bug tracker (which is psycopg3, which doesn't implement replication support yet). I suggest you to ask your question on the pgsql-general mailing list.
