### ISSUE TITLE
Connection pool - Verbose INFO logs

### ISSUE THREAD

**Issue by rustprooflabs** [psycopg/psycopg3#43]
The log output from `INFO` level when using the connection pool is quite verbose.  Each query handled by the pool generates 3 log entries, that gets rather large with even a modest amount of query activity.  Would these 3 messages be more appropriate for the `DEBUG` level?

```bash
2021-03-29 17:50:40,458 INFO psycopg3.pool.pool Thread-2 : connection requested from 'pool-1'
2021-03-29 17:50:40,458 INFO psycopg3.pool.pool Thread-2 : connection given by 'pool-1'
2021-03-29 17:50:40,588 INFO psycopg3.pool.pool Thread-2 : returning connection to 'pool-1'
```

Version tested

```pip freeze | grep psycopg3
psycopg3 @ git+https://github.com/psycopg/psycopg3.git@b270a0fe2f66c870e7eb2e1baa79b65330c3d752#subdirectory=psycopg3
```

**Comment by dvarrazzo** [comment]
Maybe so, I thought about that. But at debug level there would be even more noise from the connection (which has a different name anyway, so there is the possibility to customise receiving only one and not the other).

I think the names of the loggers would also need some tweaking. `psycogp3.pool.pool` is an internal name, `psycopg3.pool` would be better there...

Which ones do you think are meaningful messages to emit at INFO level? Would you like to try and tweak the debug levels a bit to obtain a meaningful stream of messages in your application?

**Comment by asqui** [comment]
I believe the way this is handled in, for example, sqlalchemy, is that you have a well-known logger (e.g. `psycopg3.pool` in this case) but the level for that logger is set to `WARNING` or `ERROR` by default, so that if you want more diagnostic information you can opt-in to it by explicitly lowering the level of that logger in your application.

You can even document the specific policies in use for loggers, so that users know what to expect (e.g. from memory, I believe the sqlalchemy engine logger outputs all SQL executed at INFO level, and all results retrieved from the database at DEBUG level, and this is specified in the documentation.)

**Comment by rustprooflabs** [comment]
> I believe the way this is handled in, for example, sqlalchemy, is that you have a well-known logger (e.g. `psycopg3.pool` in this case) but the level for that logger is set to `WARNING` or `ERROR` by default, so that if you want more diagnostic information you can opt-in to it by explicitly lowering the level of that logger in your application.

@asqui I was not aware of this. Adding the following appears to get me to the default level of logging I was expecting.

```python
logging.getLogger('psycopg3').setLevel(logging.WARNING)
```

It is documented here: https://docs.sqlalchemy.org/en/14/core/engines.html

> "By default, the log level is set to logging.WARN within the entire sqlalchemy namespace so that no log operations occur, even within an application that has logging enabled otherwise."

^^^ I like that!

> Which ones do you think are meaningful messages to emit at INFO level?

@dvarrazzo The most important to me is the first one, `connection requested from 'pool-1'`.  The 2nd message seems like a DEBUG, I would assume the connection was given from the pool if a subsequent warning/error was not generated. I keep going back and forth on the 3rd entry.  On one hand having the timestamp of a connection going back to the pool could be helpful, on the other hand I don't see how I could tie any given "returned to pool" back to a specific "requested from pool" message.

> Would you like to try and tweak the debug levels a bit to obtain a meaningful stream of messages in your application?

I plan to do some more experimenting and will keep an eye on the logs at different log levels.  Ultimately it seems like I just wanted to set the level to warn!

**Comment by dvarrazzo** [comment]
Thank you both for the input.

The approach I have in mind for loggers is to log but not touch the config: if an app requires logging they may increase the level. However, if it is a common practice to set the log level to warning on the base logger, we may go for it.

The reason why there are 3 messages is to monitor queued requests. In your example a connection already was available, when it isn't you would see potentially significant time between those messages.

@rustprooflabs how about I leave you playing with the integration with your application and  tweaks to the logging, including

- default level
- name of the loggers (which I'd like to document)
- level of the messages

maybe you could have an useful set of suggestions in a few days.

**Comment by rustprooflabs** [comment]
I like the default level of WARN as [SQLAlchemy handles it](https://github.com/sqlalchemy/sqlalchemy/blob/master/lib/sqlalchemy/log.py#L25-L30).  I added the following to `connection.py` and was happy with the result from the application side. The levels of various logs seem ok to me, this change reduces noise in the application logs appropriately.

```python
# set initial level to WARN.  This so that
# log statements don't occur in the absence of explicit
# logging being enabled for 'psycopg3'.
if package_logger.level == logging.NOTSET:
    package_logger.setLevel(logging.WARN)
```

I don't have a strong opinion on the names of the loggers. Right now they nicely point to the module involved, that doesn't seem like a bad thing.

**Comment by dvarrazzo** [comment]
The module involved is an implementation module: it should maybe be renamed as `psycopg3.pool._pool`. The interface module is `psycopg3.pool` (it is what appears if you inspect the class) so I would rather the logger name to match it.

I will do some experiment with setting the loglevel to WARN, thank you :)

**Comment by dvarrazzo** [comment]
@rustprooflabs would you like to check if logging behaves as you expect, on current master?

Thank you very much again for your input!

**Comment by rustprooflabs** [comment]
@dvarrazzo A quick test looks good! Thank you!

**Comment by asqui** [comment]
I noticed the SQLAlchemy code had an `if logger.level == logging.NOTSET:` guard clause and wondered why this was necessary.

I think this is intended to ensure that you don't accidentally undo a user setting a different level if they beat you to it and manage to set it _before_ psycopg is imported.

I think this is worth including for correctness...

**Comment by dvarrazzo** [comment]
@asqui I think you are right: will do :)
