### ISSUE TITLE
Feedback welcome about notifies processing design

### ISSUE THREAD

**Issue by dvarrazzo** [psycopg/psycopg3#5]
In psycopg2 connections are accumulated during the normal querying process into a list on the connection (the [`notifies` attribute](https://www.psycopg.org/docs/connection.html#connection.notifies)), which has to be emptied periodically. If someone wants to read notifications explicitly (which is the most common use case, as you have to `LISTEN` explicitly in order to receive them) then you can use `conn.poll()` in a loop to receive notifications without running additional queries, and you can block and wait for readiness on the connection fd to avoid the loop to burn cpu uselessly and still receive notifications in a timely fashion. An example of usage is [in the docs](https://www.psycopg.org/docs/advanced.html#asynchronous-notifications).

The shortcomings are the use of a list as a poor man's queue (although from psycopg2 2.7 the attribute is writable and it can be replaced by a better object) and that implementing a push loop requires dabbling with low level I/O multiplexing primitives such as `select`.

As of dc378b8f there are two ways to manage async notifications in psycopg3:

1: read them explicitly from a dedicated connection using the `connection.notifies()` generator, which will do the wait internally "the best possible way" (i.e. consistently with how the connection waits in the normal query process): notifications can be read just by a `for n in conn.notifies()` which can be left in a thread/greenlet/process of its own or block the main loop if used in a microservice that does only this - e.g. reading notifies from postgres and push them into rabbitmq... The generator can be stopped by `send()`ing it a `True` value and is an async generator for asyncio-based connections (i.e. it can be consumed using `async for n in conn.notifies()`)

2: as a callback to process notifies generated during the normal querying process: you can `conn.add_notify_handler(queue.put_nowait)` and receive notifies there as the `cursor.execute()` returns a value.

You can see samples of both the uses in the tests committed in the changeset above.

I am not entirely convinced about this design. I don't think 2. is badly needed but I wouldn't know how to process notifies in-sync with the queries otherwise. I don't see the latter a very common use case anyway but I don't want to preclude it altogether.

What do you think about the matter? Comments are welcome. Cheers!

**Comment by aklaver** [comment]
I'm still having problems wrapping my head around asyncio so I will leave that part alone.  I don't fully follow the other methods at this time. It's going to require me downloading the latest dev code and actually using it. Still I like the overall concept.
